In [8]:
from model import HydraNet
from config import device, base_output
import matplotlib.pyplot as plt
from torchvision import transforms
from PIL import Image

In [6]:
model = HydraNet().to(device=device)
model.load_state_dict(torch.load('output/model.pth'))
model.eval()

HydraNet(
  (net): ResNet(
    (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace=True)
    (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (layer1): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (1): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_runnin

In [19]:
img = Image.open(f'{base_output}/30_0_0.jpg').resize((32, 32))
totensor = transforms.ToTensor()
img_tensor = transforms.ToTensor()(img).unsqueeze(0).to(device=device)

In [20]:
output = model(img_tensor)

In [21]:
output

(tensor([[52.9012]], device='cuda:0', grad_fn=<AddmmBackward0>),
 tensor([[0.6790]], device='cuda:0', grad_fn=<AddmmBackward0>),
 tensor([[ 4.6533, -1.4066, -1.0129, -1.0520, -1.2572]], device='cuda:0',
        grad_fn=<AddmmBackward0>))